name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest # prevents intermittent Chrome Headless error unlike ubuntu
    name: Ruby ${{ matrix.version }}
    strategy:
      matrix:
        version: ['3.1', '3.2', '3.3']

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Cache node modules
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@dffc446db9ba5a0c4446edb5bca1c5c473a806c5 # v1.235.0
        with:
          ruby-version: ${{ matrix.version }}
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '18'
      - name: Install Yarn Dependencies
        run: yarn
      - name: Run Yarn Tests
        run: yarn test
      - name: Run Ruby Tests
        run: bundle exec rake test
